name: Build, Test, Scan

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm test -- --coverage
      env:
        CI: 'true'
    - uses: actions/upload-artifact@master
      with:
        name: built-app
        path: build
    - name: Commit coverage # This is the step name that will be displayed in your runs
      uses: EndBug/add-and-commit@v2.1.0 # You can change this to use a specific version
      with: # See more info about inputs below
        author_name: GitHub Actions
        author_email: na
        message: "test coverage report"
        path: "."
        pattern: "coverage/*"
        force: 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
    # - uses: sonarsource/sonarcloud-github-action@master
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
