name: Build, Test, Scan, 11y

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
#     - name: npm install, build, and test
#       run: |
#         npm install
#         npm run build --if-present
#         npm test -- --coverage
#       env:
#         CI: 'true'
    - name: LFS get
      run: |
        git lfs install
        npm install
    - name: Hello world  step
      id: hello
      uses: bengm/docker-action@master
      with:
        who-to-greet: 'Mona the Octocat'
    
   
